version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: trading_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/trading_db
      - BINANCE_WS_URL=wss://fstream.binance.com/ws
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: 